add_executable(OpenGraal WIN32
        actor.cpp
        actor.hpp
        actor_move.cpp
        animation.cpp
        animation.hpp
        animation_manager.cpp
        animation_manager.hpp
        carry_object.cpp
        carry_object.hpp
        constants.hpp
        file_manager.cpp
        file_manager.hpp
        font_manager.cpp
        font_manager.hpp
        dev_input.cpp
        dev_input.hpp
        editor/editor_canvas.cpp
        editor/editor_canvas.hpp
        editor/editor_file_browser.cpp
        editor/editor_file_browser.hpp
        editor/editor_link_dialogs.cpp
        editor/editor_link_dialogs.hpp
        editor/editor_script_dialog.cpp
        editor/editor_script_dialog.hpp
        editor/editor_sign_dialog.cpp
        editor/editor_sign_dialog.hpp
        editor/editor_ops.cpp
        editor/editor_ops.hpp
        editor/editor_palette.cpp
        editor/editor_palette.hpp
        editor/editor_profiles.cpp
        editor/editor_profiles.hpp
        editor/editor_screen.cpp
        editor/editor_screen.hpp
        editor/editor_state.hpp
        gui/gui_frame_set_ctrl.cpp
        gui/gui_frame_set_ctrl.hpp
        gui/gui_scrollbar_ctrl.cpp
        gui/gui_scrollbar_ctrl.hpp
        game.cpp
        game.hpp
        gui/gui.hpp
        gui/gui_bitmap_button_ctrl.cpp
        gui/gui_bitmap_button_ctrl.hpp
        gui/gui_button_base_ctrl.cpp
        gui/gui_button_base_ctrl.hpp
        gui/gui_button_ctrl.cpp
        gui/gui_button_ctrl.hpp
        gui/gui_check_box_ctrl.cpp
        gui/gui_check_box_ctrl.hpp
        gui/gui_context_menu_ctrl.cpp
        gui/gui_context_menu_ctrl.hpp
        gui/gui_control.cpp
        gui/gui_control.hpp
        gui/gui_control_profile.cpp
        gui/gui_control_profile.hpp
        gui/gui_drawing_panel.cpp
        gui/gui_drawing_panel.hpp
        gui/gui_ml_text_ctrl.cpp
        gui/gui_ml_text_ctrl.hpp
        gui/gui_ml_text_edit_ctrl.cpp
        gui/gui_ml_text_edit_ctrl.hpp
        gui/gui_popup_menu_ctrl.cpp
        gui/gui_popup_menu_ctrl.hpp
        gui/gui_progress_ctrl.cpp
        gui/gui_progress_ctrl.hpp
        gui/gui_radio_ctrl.cpp
        gui/gui_radio_ctrl.hpp
        gui/gui_scroll_ctrl.cpp
        gui/gui_show_img_ctrl.cpp
        gui/gui_slider_ctrl.cpp
        gui/gui_slider_ctrl.hpp
        key_codes.cpp
        gui/gui_tab_ctrl.cpp
        gui/gui_text_list_ctrl.cpp
        gui/gui_tree_view_ctrl.cpp
        gui/gui_tree_view_ctrl.hpp
        gui/gui_tab_ctrl.hpp
        gui/gui_show_img_ctrl.hpp
        gui/gui_scroll_ctrl.hpp
        gui/gui_text_ctrl.cpp
        gui/gui_text_ctrl.hpp
        gui/gui_text_edit_ctrl.cpp
        gui/gui_text_edit_ctrl.hpp
        gui/gui_utils.hpp
        gui/gui_window_ctrl.cpp
        gui/gui_window_ctrl.hpp
        input.cpp
        input.hpp
        leap_effect.cpp
        leap_effect.hpp
        level.cpp
        level.hpp
        level_link.cpp
        level_link.hpp
        level_manager.cpp
        login_screen.cpp
        login_screen.hpp
        level_manager.hpp
        level_sign.cpp
        level_sign.hpp
        main.cpp
        network.cpp
        network.hpp
        remote_player.cpp
        remote_player.hpp
        chat_bar.cpp
        client_prefs.cpp
        client_prefs.hpp
        chat_bar.hpp
        script_host.cpp
        script_host.hpp
        player.cpp
        player.hpp
        player_state.cpp
        screenshot.cpp
        screenshot.hpp
        sign.cpp
        sign.hpp
        sound_manager.cpp
        sound_manager.hpp
        texture_manager.cpp
        texture_manager.hpp
        thrown_item.cpp
        thrown_item.hpp
        tileset.cpp
        tileset.hpp
        tileset_manager.cpp
        tileset_manager.hpp
        utils.cpp
        utils.hpp
)

target_sources(OpenGraal PRIVATE ${CMAKE_SOURCE_DIR}/game.rc)

target_link_libraries(OpenGraal PRIVATE graal-shared graal-gs2 graal-net raylib glfw)

target_compile_options(OpenGraal PRIVATE
        $<$<CXX_COMPILER_ID:GNU>:-Wno-changes-meaning>
)
